#!/bin/bash
# Post-removal script for academic-workflow-suite

set -e

case "$1" in
    purge)
        # Remove configuration directory on purge
        rm -rf /etc/academic-workflow-suite
        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
