#!/bin/bash
# Pre-removal script for academic-workflow-suite

set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Stop any running services if applicable
        :
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
